In [1]:
import pandas as pd

# Read metadata 

### Gives IDs for the names of the columns. Necessary because this data uses layered indexes

I.E. DP05_0001E maps to Estimate!!SEX AND AGE!!Total population, which is the Estimate of the total population given in the Sex and Age section

In [5]:
metadata = pd.read_csv("./Demographic_And_Housing-Column-Metadata.csv")
metadata

     Column Name                                              Label
0         GEO_ID                                          Geography
1           NAME                               Geographic Area Name
2     DP05_0001E            Estimate!!SEX AND AGE!!Total population
3     DP05_0001M     Margin of Error!!SEX AND AGE!!Total population
4     DP05_0002E      Estimate!!SEX AND AGE!!Total population!!Male
..           ...                                                ...
361  DP05_0089PM  Percent Margin of Error!!CITIZEN, VOTING AGE P...
362  DP05_0090PE  Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...
363  DP05_0090PM  Percent Margin of Error!!CITIZEN, VOTING AGE P...
364  DP05_0091PE  Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...
365  DP05_0091PM  Percent Margin of Error!!CITIZEN, VOTING AGE P...

[366 rows x 2 columns]

# Read base data from the CSV

In [7]:
data = pd.read_csv("./Demographic_And_Housing-Data.csv")
data

,GEO_ID,NAME,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,...,DP05_0087PM,DP05_0088PE,DP05_0088PM,DP05_0089PE,DP05_0089PM,DP05_0090PE,DP05_0090PM,DP05_0091PE,DP05_0091PM,Unnamed: 366
0,Geography,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Sex r...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!Total housing units,Percent Margin of Error!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...",NaN
1,0500000US01003,"Baldwin County, Alabama",246435,*****,120664,1277,125771,1277,95.9,2.0,...,0.9,(X),(X),189876,(X),48.1,0.4,51.9,0.4,NaN
2,0500000US01015,"Calhoun County, Alabama",115788,*****,56554,791,59234,791,95.5,2.6,...,0.8,(X),(X),90642,(X),47.8,0.3,52.2,0.3,NaN
3,0500000US01043,"Cullman County, Alabama",90665,*****,45051,622,45614,622,98.8,2.7,...,0.6,(X),(X),69096,(X),49.0,0.6,51.0,0.6,NaN
4,0500000US01049,"DeKalb County, Alabama",71998,*****,36024,566,35974,566,100.1,3.2,...,0.6,(X),(X),52110,(X),49.6,0.9,50.4,0.9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
844,0500000US72113,"Ponce Municipio, Puerto Rico",132138,*****,62755,*****,69383,*****,90.4,*****,...,N,(X),(X),108813,(X),46.9,0.2,53.1,0.2,NaN
845,0500000US72127,"San Juan Municipio, Puerto Rico",334776,*****,152697,*****,182079,*****,83.9,*****,...,0.3,(X),(X),267707,(X),44.4,0.4,55.6,0.4,NaN
846,0500000US72135,"Toa Alta Municipio, Puerto Rico",66041,*****,30992,507,35049,507,88.4,2.7,...,N,(X),(X),54929,(X),47.0,0.2,53.0,0.2,NaN
847,0500000US72137,"Toa Baja Municipio, Puerto Rico",72783,*****,34120,462,38663,462,88.2,2.3,...,N,(X),(X),59675,(X),44.9,0.7,55.1,0.7,NaN
848,0500000US72139,"Trujillo Alto Municipio, Puerto Rico",66810,*****,31251,1847,35559,1847,87.9,9.7,...,N,(X),(X),55294,(X),46.4,0.9,53.6,0.9,NaN