## Merge COVID data with Employment data

In [68]:
import pandas as pd
import numpy as np

covid = pd.read_csv('../Full_Covid_Data.csv')
employment = pd.read_csv('Employment2020-2022.csv')
employment.tail()

,Unnamed: 0,area_fips,area_title_2020,agglvl_title_2020,annual_avg_estabs_count_2020,annual_avg_emplvl_2020,total_annual_wages_2020,taxable_annual_wages_2020,annual_contributions_2020,annual_avg_wkly_wage_2020,...,oty_total_annual_wages_chg_2022,oty_total_annual_wages_pct_chg_2022,oty_taxable_annual_wages_chg_2022,oty_taxable_annual_wages_pct_chg_2022,oty_annual_contributions_chg_2022,oty_annual_contributions_pct_chg_2022,oty_annual_avg_wkly_wage_chg_2022,oty_annual_avg_wkly_wage_pct_chg_2022,oty_avg_annual_pay_chg_2022,oty_avg_annual_pay_pct_chg_2022
4424,4424,CS566,"Youngstown-Warren, OH-PA CSA","CMSA or CSA, Total Covered",15189,218640,9526487285,1911917573,48434989,838,...,680629411,6.7,77277597,3.9,2189314,4.0,39,4.4,2067,4.5
4425,4425,US000,U.S. TOTAL,"National, Total Covered",10487687,139103773,8905606771748,1701611855984,29184310012,1231,...,778774756312,8.0,162185375499,8.8,127404523,0.4,46,3.5,2376,3.5
4426,4426,USCMS,U.S. Combined Statistical Areas (combined),"Total, all U.S. CMSAs or all U.S. CSAs",7525743,106280879,7082448329217,1313653139572,23132428602,1282,...,535181314882,7.0,120077517928,8.5,51424249,0.2,39,2.9,2017,2.9
4427,4427,USMSA,U.S. Metropolitan Statistical Areas (combined),"Total, all U.S. MSAs",8472291,120199570,7900946148624,1453364235640,25361693284,1264,...,616603104921,7.2,132306819289,8.5,-51626434,-0.2,41,3.1,2089,3.0
4428,4428,USNMS,U.S. Nonmetropolitan Area Counties (combined),"Total, all U.S. non-MSA counties",2015396,18904204,1004660623124,248247620344,3822616728,1022,...,162171651391,14.2,29878556210,10.8,179030957,3.8,84,7.6,4340,7.6

In [69]:
covid.columns = covid.columns.str.replace('countyFIPS', 'area_fips')
covid['area_fips'] = np.where(covid['area_fips'] == 0, covid['StateFIPS_deaths'], covid['area_fips'])
covid.area_fips = covid.area_fips.astype(str)
employment.area_fips = employment.area_fips.astype(str)
employment.area_fips = employment.area_fips.str.replace("000", "")

covid_employment = covid.merge(employment, on='area_fips', how='outer')
covid_employment

,Unnamed: 0_x,area_fips,County Name_deaths,State,StateFIPS_deaths,2020-01-22_deaths,2020-01-23_deaths,2020-01-24_deaths,2020-01-25_deaths,2020-01-26_deaths,...,oty_total_annual_wages_chg_2022,oty_total_annual_wages_pct_chg_2022,oty_taxable_annual_wages_chg_2022,oty_taxable_annual_wages_pct_chg_2022,oty_annual_contributions_chg_2022,oty_annual_contributions_pct_chg_2022,oty_annual_avg_wkly_wage_chg_2022,oty_annual_avg_wkly_wage_pct_chg_2022,oty_avg_annual_pay_chg_2022,oty_avg_annual_pay_pct_chg_2022
0,0.0,1,Statewide Unallocated,AL,1.0,0.0,0.0,0.0,0.0,0.0,...,9.290719e+09,8.7,8.418009e+08,5.1,-48478330.0,-18.1,57.0,5.5,2951.0,5.4
1,1.0,1001,Autauga County,AL,1.0,0.0,0.0,0.0,0.0,0.0,...,4.771316e+07,9.7,5.304830e+06,6.4,-248549.0,-17.6,50.0,5.9,2563.0,5.8
2,2.0,1003,Baldwin County,AL,1.0,0.0,0.0,0.0,0.0,0.0,...,3.863482e+08,11.5,4.580940e+07,6.7,-1708060.0,-16.4,56.0,6.6,2942.0,6.7
3,3.0,1005,Barbour County,AL,1.0,0.0,0.0,0.0,0.0,0.0,...,2.326714e+07,7.5,9.514080e+05,1.5,-215205.0,-21.3,47.0,6.1,2441.0,6.1
4,4.0,1007,Bibb County,AL,1.0,0.0,0.0,0.0,0.0,0.0,...,1.660473e+07,7.6,5.683300e+04,0.2,-108080.0,-19.0,51.0,5.8,2675.0,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4450,NaN,CS566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.806294e+08,6.7,7.727760e+07,3.9,2189314.0,4.0,39.0,4.4,2067.0,4.5
4451,NaN,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.787748e+11,8.0,1.621854e+11,8.8,127404523.0,0.4,46.0,3.5,2376.0,3.5
4452,NaN,USCMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.351813e+11,7.0,1.200775e+11,8.5,51424249.0,0.2,39.0,2.9,2017.0,2.9
4453,NaN,USMSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.166031e+11,7.2,1.323068e+11,8.5,-51626434.0,-0.2,41.0,3.1,2089.0,3.0
4454,NaN,USNMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.621717e+11,14.2,2.987856e+10,10.8,179030957.0,3.8,84.0,7.6,4340.0,7.6

In [70]:
covid_employment.dropna(axis=0)
covid_employment = covid_employment[covid_employment.columns.drop(covid_employment.filter(regex='Unnamed:'))]
covid_employment.head()

,area_fips,County Name_deaths,State,StateFIPS_deaths,2020-01-22_deaths,2020-01-23_deaths,2020-01-24_deaths,2020-01-25_deaths,2020-01-26_deaths,2020-01-27_deaths,...,oty_total_annual_wages_chg_2022,oty_total_annual_wages_pct_chg_2022,oty_taxable_annual_wages_chg_2022,oty_taxable_annual_wages_pct_chg_2022,oty_annual_contributions_chg_2022,oty_annual_contributions_pct_chg_2022,oty_annual_avg_wkly_wage_chg_2022,oty_annual_avg_wkly_wage_pct_chg_2022,oty_avg_annual_pay_chg_2022,oty_avg_annual_pay_pct_chg_2022
0,1,Statewide Unallocated,AL,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.290719e+09,8.7,841800853.0,5.1,-48478330.0,-18.1,57.0,5.5,2951.0,5.4
1,1001,Autauga County,AL,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.771316e+07,9.7,5304830.0,6.4,-248549.0,-17.6,50.0,5.9,2563.0,5.8
2,1003,Baldwin County,AL,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.863482e+08,11.5,45809405.0,6.7,-1708060.0,-16.4,56.0,6.6,2942.0,6.7
3,1005,Barbour County,AL,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.326714e+07,7.5,951408.0,1.5,-215205.0,-21.3,47.0,6.1,2441.0,6.1
4,1007,Bibb County,AL,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.660473e+07,7.6,56833.0,0.2,-108080.0,-19.0,51.0,5.8,2675.0,5.8

In [72]:
covid_employment.to_csv('Merge_Covid_Employment.csv')